name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    # Frontend
    # Install based on package-lock.json in frontend
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    # Run build script : "tsc -b && vite build --mode production" in package.json
    # tsc - b type checks the code in build mode, using tsconfig.json which
    # references tsconfig.app.json and tsconfig.node.json
    - name: Build frontend
      working-directory: frontend
      run: npm run FE:build:production

    # Run tests in frontend
    # --watchAll=false ensures tests run once and exit
    - name: Test frontend
      working-directory: frontend
      run: npm test -- --watchAll=false

    # Backend
    - name: Install backend dependencies
      working-directory: backend
      run: npm ci



