name: Docker Build & Publish
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write  # allow pushing to GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_FRONTEND: ghcr.io/${{ github.repository }}/frontend
  IMAGE_BACKEND: ghcr.io/${{ github.repository }}/backend

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Frontend metadata
        id: meta_fe
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_FRONTEND }}
          tags: |
            type=ref,event=branch
            type=raw,value=sha-${{ github.sha }}

      - name: Backend metadata
        id: meta_be
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_BACKEND }}
          tags: |
            type=ref,event=branch
            type=raw,value=sha-${{ github.sha }}

      - name: Build & push FRONTEND image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          build-args: |
            VITE_BACKEND_ORIGIN=${{ secrets.VITE_BACKEND_ORIGIN }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_fe.outputs.tags }}
          labels: ${{ steps.meta_fe.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push BACKEND image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_be.outputs.tags }}
          labels: ${{ steps.meta_be.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
